version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: elasticsearch-8.4.1
    environment:
      - node.name=es
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - network.host=0.0.0.0
      - http.port=9200
      - xpack.security.enabled=false

    user: elasticsearch
    volumes:
      - /share/Container/elasticsearch/data:/usr/share/elasticsearch/data
      - /share/Container/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - net
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.4.1
    container_name: kibana-8.4.1
    volumes:
      - /share/Container/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - net
    ports:
      - "5601:5601"

  filebeat:
    depends_on:
      - elasticsearch
      - mosquitto
    image: docker.elastic.co/beats/filebeat:8.4.1
    container_name: filebeat-8.4.1
    # Need to override user so we can access the log files, and docker.sock
    user: root
    volumes:
      - /share/Container/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - net
    # disable strict permission checks
    command: ["--strict.perms=false"]

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    networks:
      - net
    ports:
      # mqtt
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /share/Container/mosquitto:/mosquitto

networks:
  net:
